### ISSUE TITLE
the use of pipes with one function statements is discouraged

### ISSUE THREAD

**Issue by aaronpeikert** [romatik/touring_the_tidyverse#2]
Many workshops advise  you that you should abstain from using the pipe, when there is only one function. Because instead of increasing readability it decrease it.

#Example:

   iris %>% head() #low readability
vs.
   head(iris) # high readability

while:

   iris %>% select(Petal.Width, Species) %>% head() # high readability
vs.
   head(select(iris, Petal.Width, Species)) #low readability

**Comment by romatik** [comment]
The style that I'm trying to follow myself is similar to what you mention with one small caveat: I prefer to put the dataframe I work with explicitly on the first row like this:
```
iris %>% 
  head()
```
instead of 
```
iris %>% head()
```
even if it's only one function. I should be more consistent with this myself, but that is at least the style that I want to have in all of my code.

Reason for that is rather superficial since to me it looks more consistent then switching back and forth between two styles where you need to decide in advance how many steps your code is going to have and if it is 1 then use `head(iris)` approach and if it is two more than use pipe.

**Comment by aaronpeikert** [comment]
@romatik shure if that is your style. However maybe it would be good to have a talk about the tidyverse styleguide to in the series: http://style.tidyverse.org
